In [1]:
import sklearn as sk

In [2]:
sk.__version__

'0.20.3'

In [3]:
from sklearn import svm

In [4]:
xor_data = [
    # P, Q, result
    [0, 0, 0],
    [0, 1,  1],
    [1,  0, 1],
    [1, 1, 0]
]

In [5]:
xor_data

[[0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0]]

In [22]:
import numpy as np

In [23]:
xor_data_np = np.array(xor_data)

In [24]:
xor_data_np

array([[0, 0, 0],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

## 데이터 분리하기

In [6]:
data = []

In [7]:
label = []

In [8]:
for row in xor_data :
    p = row[0]
    q = row[1]
    r = row[2]
    data.append([p,q])
    print(data)
    label.append(r)

[[0, 0]]
[[0, 0], [0, 1]]
[[0, 0], [0, 1], [1, 0]]
[[0, 0], [0, 1], [1, 0], [1, 1]]


In [9]:
data

[[0, 0], [0, 1], [1, 0], [1, 1]]

In [10]:
label

[0, 1, 1, 0]

### 넘파이 모듈을 이용해서 처리하기 

In [27]:
data_np = xor_data_np[:, [0,1]]

In [28]:
data_np

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [29]:
label_np = xor_data_np[:, [2]]

In [30]:
label_np

array([[0],
       [1],
       [1],
       [0]])

### 1차원으로 축소 

In [34]:
label_np.shape

(4, 1)

In [35]:
label_np = label_np.reshape(4)

In [38]:
label_np.shape

(4,)

## 데이터 학습하기

In [11]:
clf = svm.SVC(gamma='auto')

In [12]:
clf

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [13]:
clf.fit(data, label)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

### 넘파이 모듈로 데이터 변환

In [31]:
clf_np = svm.SVC(gamma='auto')

In [36]:
clf_np.fit(data_np , label_np)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

## 데이터 예측하기

In [14]:
pre = clf.predict(data)

In [15]:
pre

array([0, 1, 1, 0])

### 넘파이로 예측하기 

In [40]:
pre_np = clf_np.predict(data_np)

In [41]:
pre_np

array([0, 1, 1, 0])

## 결과 확인하기

In [16]:
ok = 0; total = 0

In [17]:
for idx, answer in enumerate(label) :
    p = pre[idx]
    if p == answer :
        ok += 1
    total +=  1
    


In [18]:
ok

4

In [19]:
total

4

In [20]:
pre

array([0, 1, 1, 0])