In [1]:
import sklearn.preprocessing as pre

In [13]:
for i in dir(pre) :
    print(i) if not i.startswith("_") else _

Binarizer
FunctionTransformer
KBinsDiscretizer
KernelCenterer
LabelBinarizer
LabelEncoder
MaxAbsScaler
MinMaxScaler
MultiLabelBinarizer
Normalizer
OneHotEncoder
OrdinalEncoder
PolynomialFeatures
PowerTransformer
QuantileTransformer
RobustScaler
StandardScaler
add_dummy_feature
binarize
label_binarize
maxabs_scale
minmax_scale
normalize
power_transform
quantile_transform
robust_scale
scale


In [2]:
import numpy as np

In [4]:
f = np.array([[-550.5],
            [-100.1],
            [0.0],
            [100.1],
            [900.9]])

In [5]:
f

array([[-550.5],
       [-100.1],
       [   0. ],
       [ 100.1],
       [ 900.9]])

In [6]:
mm_s = pre.MinMaxScaler(feature_range=(0,1))

In [7]:
f_mm_s = mm_s.fit_transform(f)

In [8]:
f_mm_s

array([[0.        ],
       [0.31032107],
       [0.37928896],
       [0.44825686],
       [1.        ]])

In [15]:
st_s = pre.StandardScaler()

In [16]:
f_st_s = st_s.fit_transform(f)

In [17]:
f_st_s

array([[-1.31701572],
       [-0.36116171],
       [-0.14872613],
       [ 0.06370945],
       [ 1.76319411]])

In [18]:
rb_s = pre.RobustScaler()

In [19]:
f_rb_s = rb_s.fit_transform(f)

In [20]:
f_rb_s

array([[-2.74975025],
       [-0.5       ],
       [ 0.        ],
       [ 0.5       ],
       [ 4.5       ]])

In [10]:
ma_s = pre.MaxAbsScaler()

In [11]:
f_ma_s = ma_s.fit_transform(f)

In [12]:
f_ma_s

array([[-0.61105561],
       [-0.11111111],
       [ 0.        ],
       [ 0.11111111],
       [ 1.        ]])