In [2]:
import sklearn.feature_extraction as fe

In [13]:
for i in dir(fe) :
    print(i) if not i.startswith("_") else _

DictVectorizer
FeatureHasher
grid_to_graph
image
img_to_graph
text


In [10]:
d = [{'지방자치' : "서울시"},
     {'지방자치' : "경기도"}, 
     {'지방자치' : "광주"}]

In [11]:
dic = fe.DictVectorizer()

In [12]:
dic.fit_transform(d).toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [19]:
import sklearn.preprocessing as pre

In [20]:
for i in dir(pre) :
    print(i) if not i.startswith("_") else _

Binarizer
FunctionTransformer
KBinsDiscretizer
KernelCenterer
LabelBinarizer
LabelEncoder
MaxAbsScaler
MinMaxScaler
MultiLabelBinarizer
Normalizer
OneHotEncoder
OrdinalEncoder
PolynomialFeatures
PowerTransformer
QuantileTransformer
RobustScaler
StandardScaler
add_dummy_feature
binarize
label_binarize
maxabs_scale
minmax_scale
normalize
power_transform
quantile_transform
robust_scale
scale


In [21]:
enc = pre.OneHotEncoder(handle_unknown='ignore')
X = [['Male', 1], ['Female', 3], ['Female', 2]]
enc.fit(X)

OneHotEncoder(handle_unknown='ignore')

In [22]:
enc.categories_

[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]

In [23]:
enc.transform([['Female', 1], ['Male', 4]]).toarray()

array([[1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [24]:
enc.inverse_transform([[0, 1, 1, 0, 0], [0, 0, 0, 1, 0]])

array([['Male', 1],
       [None, 2]], dtype=object)

In [25]:
enc1 = pre.OneHotEncoder(handle_unknown='ignore')

In [27]:
enc1.fit_transform(X).toarray()

array([[0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.]])

In [15]:
import sklearn.feature_selection as fs

In [16]:
for i in dir(fs) :
    print(i) if not i.startswith("_") else _

GenericUnivariateSelect
RFE
RFECV
SelectFdr
SelectFpr
SelectFromModel
SelectFwe
SelectKBest
SelectPercentile
SelectorMixin
SequentialFeatureSelector
VarianceThreshold
chi2
f_classif
f_oneway
f_regression
mutual_info_classif
mutual_info_regression


In [18]:
!pip show scikit-learn

Name: scikit-learn
Version: 0.24.1
Summary: A set of python modules for machine learning and data mining
Home-page: http://scikit-learn.org
Author: None
Author-email: None
License: new BSD
Location: /Users/dahlmoon/anaconda3/lib/python3.7/site-packages
Requires: joblib, scipy, threadpoolctl, numpy
Required-by: yellowbrick, umap-learn, tune-sklearn, suod, shap, scikit-plot, scikit-optimize, pyod, pycaret-nightly, Orange3, openTSNE, ngboost, mlxtend, lightgbm, kmodes, imbalanced-learn, dask-ml, dask-glm, dabl, combo, Boruta, bayesian-optimization
